[meta]
name = "go"
url = "https://golang.google.cn"
version = "1.0.0"

[install]
base_dir = "golang"
method = "download"

[install.asset]
"aarch64-apple-darwin" = {default = "https://golang.google.cn/dl/go{version}.darwin-arm64.tar.gz", "go.dev" = "https://go.dev/dl/go{version}.darwin-arm64.tar.gz"}
"x86_64-apple-darwin" = {default = "https://golang.google.cn/dl/go{version}.darwin-amd64.tar.gz", "go.dev" = "https://go.dev/dl/go{version}.darwin-amd64.tar.gz"}
"x86_64-pc-windows-msvc" = {default = "https://golang.google.cn/dl/go{version}.windows-amd64.zip", "go.dev" = "https://go.dev/dl/go{version}.windows-amd64.zip"}
"x86_64-unknown-linux-gnu" = {default = "https://golang.google.cn/dl/go{version}.linux-amd64.tar.gz", "go.dev" = "https://go.dev/dl/go{version}.linux-amd64.tar.gz"}

[env]
GOBIN = "$GOPATH/bin"
GOPATH = "{user}/go"
GOROOT = "."
PATH = "bin"
