#:schema ./schema/plugin.schema.json

[meta]
name = "llvm"
url = "https://llvm.org"
version = "1.0.0"

[install]
base_dir = "llvm"
method = "download"

[install.asset]
# https://mirrors.tuna.tsinghua.edu.cn/github-release/llvm/llvm-project/LLVM%2023.1.0/clang%2Bllvm-23.1.0-x86_64-pc-windows-msvc.tar.xz
"aarch64-apple-darwin" = {default = "https://github.com/llvm/llvm-project/releases/download/llvmorg-{version}/clang+llvm-{version}-arm64-apple-darwin22.0.tar.xz", tsinghua = "https://mirrors.tuna.tsinghua.edu.cn/github-release/llvm/llvm-project/LLVM%2023.1.0/clang%2Bllvm-{version}-arm64-apple-darwin22.0.tar.xz"}
"x86_64-pc-windows-msvc" = {default = "https://github.com/llvm/llvm-project/releases/download/llvmorg-{version}/clang+llvm-{version}-x86_64-pc-windows-msvc.tar.xz", tsinghua = "https://mirrors.tuna.tsinghua.edu.cn/github-release/llvm/llvm-project/LLVM%2023.1.0/clang%2Bllvm-{version}-x86_64-pc-windows-msvc.tar.xz"}
"x86_64-unknown-linux-gnu" = {default = "https://github.com/llvm/llvm-project/releases/download/llvmorg-{version}/clang+llvm-{version}-x86_64-linux-gnu-ubuntu-18.04.tar.xz", tsinghua = "https://mirrors.tuna.tsinghua.edu.cn/github-release/llvm/llvm-project/LLVM%2023.1.0/clang%2Bllvm-{version}-x86_64-linux-gnu-ubuntu-18.04.tar.xz"}

# Windows ships a silent .exe installer (Inno Setup); macOS/Linux unpack a tarball.
# [install.strategy]
# "x86_64-pc-windows-msvc" = {method = "installer", args = ["/VERYSILENT", "/NORESTART", "/DIR={base}"]}

[env]
PATH = "bin"
